/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package books.data.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Books service. Represents a row in the &quot;ZU_Books&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link books.data.model.impl.BooksModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link books.data.model.impl.BooksImpl}.
 * </p>
 *
 * @author zubair
 * @see Books
 * @see books.data.model.impl.BooksImpl
 * @see books.data.model.impl.BooksModelImpl
 * @generated
 */
@ProviderType
public interface BooksModel extends BaseModel<Books>, GroupedModel, ShardedModel,
	StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a books model instance should use the {@link Books} interface instead.
	 */

	/**
	 * Returns the primary key of this books.
	 *
	 * @return the primary key of this books
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this books.
	 *
	 * @param primaryKey the primary key of this books
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this books.
	 *
	 * @return the uuid of this books
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this books.
	 *
	 * @param uuid the uuid of this books
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the book ID of this books.
	 *
	 * @return the book ID of this books
	 */
	public long getBookId();

	/**
	 * Sets the book ID of this books.
	 *
	 * @param bookId the book ID of this books
	 */
	public void setBookId(long bookId);

	/**
	 * Returns the group ID of this books.
	 *
	 * @return the group ID of this books
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this books.
	 *
	 * @param groupId the group ID of this books
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this books.
	 *
	 * @return the company ID of this books
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this books.
	 *
	 * @param companyId the company ID of this books
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this books.
	 *
	 * @return the user ID of this books
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this books.
	 *
	 * @param userId the user ID of this books
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this books.
	 *
	 * @return the user uuid of this books
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this books.
	 *
	 * @param userUuid the user uuid of this books
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this books.
	 *
	 * @return the user name of this books
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this books.
	 *
	 * @param userName the user name of this books
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this books.
	 *
	 * @return the create date of this books
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this books.
	 *
	 * @param createDate the create date of this books
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this books.
	 *
	 * @return the modified date of this books
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this books.
	 *
	 * @param modifiedDate the modified date of this books
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the title of this books.
	 *
	 * @return the title of this books
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this books.
	 *
	 * @param title the title of this books
	 */
	public void setTitle(String title);

	/**
	 * Returns the author of this books.
	 *
	 * @return the author of this books
	 */
	@AutoEscape
	public String getAuthor();

	/**
	 * Sets the author of this books.
	 *
	 * @param author the author of this books
	 */
	public void setAuthor(String author);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Books books);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Books> toCacheModel();

	@Override
	public Books toEscapedModel();

	@Override
	public Books toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}